shiro:
  realm: com.iyihua.commerce.web.seller.config.security.MyRealm
  loginUrl: http://login.commerce.com:8081/view/sign-in.html
  successUrl: /item.html
  unauthorizedUrl: /forbidden.html
  filterChainDefinitions:
    "/login": anon
    "/view/sign-in": anon
    "/sign-up": anon
    "/user/**": anon
    "/view/**": anon
    "/css/**": anon
    "/static/**": anon
    "/bower_components/**": anon
    "/app/**": anon
    "/lib/**": anon
    "/auth": anon
    "/account/**": anon
    "/index.html": anon
    "/about.html": anon
    "/logout": anon
    "/**": super
  enableShareJsession: true
  shareJsessionKey: SHAREJSESSIONID
  domain: .commerce.com
  path: /